name: oxy
description: A modern, feature-rich HTTP client for Dart with Web API compatibility, supporting fetch-like syntax, request/response handling, and cross-platform adapters.
version: 0.0.4
repository: https://github.com/medz/oxy

topics:
  - http
  - fetch
  - web
  - request
  - response

funding:
  - https://github.com/sponsors/medz
  - https://opencollective.com/openodroe

resolution: workspace
environment:
  sdk: ^3.8.0

dependencies:
  mime: ^2.0.0
